logging:
  outputLevel: "debug"
  #outputStderr: false
  #filePath: "explorer.log"
  #fileLevel: "warn"

# HTTP Server configuration
server:
  host: "localhost" # Address to listen on
  port: "8080" # Port to listen on

endpoints:
  - name: "pk01"
    url: "http://10.16.71.108:5052"
    priority: 4
    archive: true
  - name: "lh"
    url: "http://10.16.97.2:5052"
    priority: 5
  - name: "teku"
    url: "http://10.16.97.3:5051"
    priority: 5

pool:
  followDistance: 10

frontend:
  enabled: true # Enable or disable to web frontend
  debug: true
  minimize: false
  siteName: "Dugtrio"
