name: Go Test

on:
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:
    
jobs:
  full_ci:
    strategy:
      matrix:
        go_version: [ 1.21.x ]

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: ${{ matrix.go_version }}
        
      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@f54c4b21ff43e36adfe5fb7e6a31be8e2512abf4 # v0.5.1
        with:
          test-results: test.json
